services:
  redis:
    image: redis:7.4-alpine
    container_name: nestjs_redis_cache
    restart: always
    env_file: .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --loglevel ${REDIS_LOG_LEVEL:-warning}
      --maxmemory ${REDIS_MAX_MEMORY:-256mb}
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - redis_network

  # Opcional: Redis Commander para administración visual
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nestjs_redis_commander
    restart: always
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - redis_network

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
